#pragma once

#include <Core/Core.h>
#include <Editor/Common.h>

namespace Vortex {

namespace Action {

enum Constants {
    MAX_RECENT_FILES = 99,
    MAX_NOTESKINS = 99,
};

/// Enumeration of global actions that can be performed by the editor.
enum Type {

    NONE,

    EXIT_PROGRAM,

    FILE_OPEN,
    FILE_SAVE,
    FILE_SAVE_AS,
    FILE_CLOSE,

    FILE_OPEN_RECENT_BEGIN,
    FILE_OPEN_RECENT_END = FILE_OPEN_RECENT_BEGIN + MAX_RECENT_FILES,

    FILE_CLEAR_RECENT_FILES,

    OPEN_DIALOG_SONG_PROPERTIES,
    OPEN_DIALOG_CHART_PROPERTIES,
    OPEN_DIALOG_CHART_LIST,
    OPEN_DIALOG_NEW_CHART,
    OPEN_DIALOG_ADJUST_SYNC,
    OPEN_DIALOG_ADJUST_TEMPO,
    OPEN_DIALOG_ADJUST_TEMPO_SM5,
    OPEN_DIALOG_DANCING_BOT,
    OPEN_DIALOG_GENERATE_NOTES,
    OPEN_DIALOG_TEMPO_BREAKDOWN,
    OPEN_DIALOG_LABEL_BREAKDOWN,
    OPEN_DIALOG_WAVEFORM_SETTINGS,
    OPEN_DIALOG_ZOOM,
    OPEN_DIALOG_CUSTOM_SNAP,
    OPEN_DIALOG_PREVIEW_SETTINGS,

    EDIT_UNDO,
    EDIT_REDO,
    EDIT_CUT,
    EDIT_COPY,
    EDIT_PASTE,
    EDIT_PASTE_INSERT,
    EDIT_DELETE,

    TOGGLE_JUMP_TO_NEXT_NOTE,
    TOGGLE_UNDO_REDO_JUMP,
    TOGGLE_TIME_BASED_COPY,

    SET_VISUAL_SYNC_CURSOR_ANCHOR,
    SET_VISUAL_SYNC_RECEPTOR_ANCHOR,
    INJECT_BOUNDING_BPM_CHANGE,
    SHIFT_ROW_NONDESTRUCTIVE,
    SHIFT_ROW_DESTRUCTIVE,

    SELECTION_TOGGLE_TEMPO_EDITOR,

    REQUANTIZE_NOTES,

    SELECT_ALL,
    SELECT_REGION,
    SELECT_ALL_STEPS,
    SELECT_ALL_MINES,
    SELECT_ALL_HOLDS,
    SELECT_ALL_ROLLS,
    SELECT_ALL_FAKES,
    SELECT_ALL_LIFTS,
    SELECT_REGION_BEFORE_CURSOR,
    SELECT_REGION_AFTER_CURSOR,

    SELECT_QUANT_4,
    SELECT_QUANT_8,
    SELECT_QUANT_12,
    SELECT_QUANT_16,
    SELECT_QUANT_24,
    SELECT_QUANT_32,
    SELECT_QUANT_48,
    SELECT_QUANT_64,
    SELECT_QUANT_192,

    SELECT_DENSITY_BEGIN,
    SELECT_DENSITY_END = SELECT_DENSITY_BEGIN + SIM_MAX_COLUMNS,

    SELECT_TEMPO_BPM,
    SELECT_TEMPO_STOP,
    SELECT_TEMPO_DELAY,
    SELECT_TEMPO_WARP,
    SELECT_TEMPO_TIME_SIG,
    SELECT_TEMPO_TICK_COUNT,
    SELECT_TEMPO_COMBO,
    SELECT_TEMPO_SPEED,
    SELECT_TEMPO_SCROLL,
    SELECT_TEMPO_FAKE,
    SELECT_TEMPO_LABEL,

    SET_TEMPO_EDIT_CURSOR_ANCHOR,
    SET_TEMPO_EDIT_RECEPTOR_ANCHOR,
    EDIT_TEMPO_BPM,
    EDIT_TEMPO_STOP,
    EDIT_TEMPO_DELAY,
    EDIT_TEMPO_WARP,
    EDIT_TEMPO_TIME_SIG,
    EDIT_TEMPO_TICK_COUNT,
    EDIT_TEMPO_COMBO,
    EDIT_TEMPO_SPEED,
    EDIT_TEMPO_SCROLL,
    EDIT_TEMPO_FAKE,
    EDIT_TEMPO_LABEL,

    CHART_PREVIOUS,
    CHART_NEXT,
    CHART_DELETE,

    SIMFILE_PREVIOUS,
    SIMFILE_NEXT,

    CHART_CONVERT_COUPLES_TO_ROUTINE,
    CHART_CONVERT_ROUTINE_TO_COUPLES,

    CHANGE_NOTES_TO_MINES,
    CHANGE_NOTES_TO_FAKES,
    CHANGE_NOTES_TO_LIFTS,
    CHANGE_MINES_TO_NOTES,
    CHANGE_MINES_TO_FAKES,
    CHANGE_MINES_TO_LIFTS,
    CHANGE_FAKES_TO_NOTES,
    CHANGE_LIFTS_TO_NOTES,
    CHANGE_HOLDS_TO_STEPS,
    CHANGE_HOLDS_TO_MINES,
    CHANGE_BETWEEN_HOLDS_AND_ROLLS,
    CHANGE_BETWEEN_PLAYER_NUMBERS,
    CHANGE_NOTE_SIDE,

    MIRROR_NOTES_VERTICALLY,
    MIRROR_NOTES_HORIZONTALLY,
    MIRROR_NOTES_FULL,

    EXPORT_NOTES_AS_LUA_TABLE,

    SCALE_NOTES_2_TO_1,
    SCALE_NOTES_3_TO_2,
    SCALE_NOTES_4_TO_3,
    SCALE_NOTES_1_TO_2,
    SCALE_NOTES_2_TO_3,
    SCALE_NOTES_3_TO_4,

    SWITCH_TO_SYNC_MODE,

    VOLUME_RESET,
    VOLUME_INCREASE,
    VOLUME_DECREASE,
    VOLUME_MUTE,

    CONVERT_MUSIC,
    CONVERT_MUSIC_TO_OGG,
    CONVERT_MUSIC_TO_MP3,
    CONVERT_MUSIC_TO_WAV,

    SPEED_RESET,
    SPEED_INCREASE,
    SPEED_DECREASE,
    SPEED_INCREASE_FINE,
    SPEED_DECREASE_FINE,

    TOGGLE_BEAT_TICK,
    TOGGLE_NOTE_TICK,

    TOGGLE_SHOW_WAVEFORM,
    TOGGLE_SHOW_NOTES,
    TOGGLE_SHOW_TEMPO_BOXES,
    TOGGLE_SHOW_TEMPO_HELP,
    TOGGLE_REVERSE_SCROLL,
    TOGGLE_CHART_PREVIEW,

    BEATLINE_TOGGLE_ENABLED,
    BEATLINE_TOGGLE_SNAP,
    BEATLINE_TOGGLE_COLOR,
    BEATLINE_TOGGLE_HOVER,

    PREVIEW_TOGGLE_ENABLED,
    PREVIEW_TOGGLE_SHOW_BEAT_LINES,
    PREVIEW_TOGGLE_REVERSE_SCROLL,
    PREVIEW_VIEW_CMOD,
    PREVIEW_VIEW_XMOD,
    PREVIEW_VIEW_VARIABLE,

    MINIMAP_SET_NOTES,
    MINIMAP_SET_DENSITY,

    BACKGROUND_HIDE,
    BACKGROUND_INCREASE_ALPHA,
    BACKGROUND_DECREASE_ALPHA,
    BACKGROUND_SET_STRETCH,
    BACKGROUND_SET_LETTERBOX,
    BACKGROUND_SET_CROP,

    USE_TIME_BASED_VIEW,
    USE_ROW_BASED_VIEW,

    ZOOM_RESET,
    ZOOM_IN,
    ZOOM_OUT,
    SCALE_INCREASE,
    SCALE_DECREASE,

    SET_NOTESKIN_BEGIN,
    SET_NOTESKIN_END = SET_NOTESKIN_BEGIN + MAX_NOTESKINS,

    SNAP_RESET,
    SNAP_NEXT,
    SNAP_PREVIOUS,

    CURSOR_UP,
    CURSOR_DOWN,
    CURSOR_PREVIOUS_BEAT,
    CURSOR_NEXT_BEAT,
    CURSOR_PREVIOUS_MEASURE,
    CURSOR_NEXT_MEASURE,
    CURSOR_STREAM_START,
    CURSOR_STREAM_END,
    CURSOR_SELECTION_START,
    CURSOR_SELECTION_END,
    CURSOR_CHART_START,
    CURSOR_CHART_END,

    TOGGLE_STATUS_CHART,
    TOGGLE_STATUS_SNAP,
    TOGGLE_STATUS_BPM,
    TOGGLE_STATUS_ROW,
    TOGGLE_STATUS_BEAT,
    TOGGLE_STATUS_MEASURE,
    TOGGLE_STATUS_HOVER,
    TOGGLE_STATUS_TIME,
    TOGGLE_STATUS_TIMING_MODE,
    TOGGLE_STATUS_SCROLL,
    TOGGLE_STATUS_SPEED,

    SHOW_SHORTCUTS,
    SHOW_MESSAGE_LOG,
    SHOW_DEBUG_LOG,
    SHOW_ABOUT,
    OPEN_DIALOG_AUDIO_SETTINGS,
    TOGGLE_AUDIO_OFFSET,

    NUM_ACTIONS
};

// Performs the action associated with the action type.
bool perform(Type action);
};  // namespace Action

};  // namespace Vortex
